"""SQLAlchemy declarative base and shared column mixins.

Every persisted model inherits from :class:`Base` so that Alembic's
autogenerate sees a single ``MetaData`` and can diff the whole schema in one
pass.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, MetaData, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# ---------------------------------------------------------------------------
# Constraint naming convention
# ---------------------------------------------------------------------------
# Without this, PostgreSQL invents constraint names and Alembic generates
# migrations containing `op.drop_constraint(None, ...)` — which fails on
# apply. Fixing that after the fact means rewriting production constraint
# names, so it must be set before the first migration is ever generated.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class UUIDPrimaryKeyMixin:
    """A UUID primary key, generated by the application.

    UUIDs over auto-incrementing integers, for three reasons that matter to a
    multi-tenant SaaS:

    1. **No enumeration.** ``/datasets/1`` invites a customer to try
       ``/datasets/2``. Authorisation should stop them, but not leaking the
       identifier space removes a whole class of probing.
    2. **No round-trip to insert.** The id exists before the ``INSERT``, so a
       service can build an object graph and emit one flush.
    3. **Merge-safe.** Ids stay unique across environments and future shards.

    The cost is a wider index. Revisit with UUIDv7 if index locality on
    high-write tables ever shows up in profiling — it keeps these properties
    while sorting by creation time.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class TimestampMixin:
    """``created_at`` / ``updated_at``, maintained by the database.

    ``server_default``/``onupdate`` at the DB level rather than in Python, so
    the values stay correct for rows written by a migration, a bulk load, or a
    psql session — not only by the ORM. ``timezone=True`` maps to
    ``TIMESTAMPTZ``; storing naive timestamps is a bug waiting for a customer
    in another timezone.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class SoftDeleteMixin:
    """Marks a row deleted without removing it.

    Operational datasets are referenced by analyses, reports, and audit
    records. A hard delete would orphan those or cascade away a customer's
    history. Soft deletion keeps referential integrity and makes "restore
    that file I deleted yesterday" a supportable request.

    Queries must filter ``deleted_at IS NULL`` — the repository layer is
    responsible for applying that consistently so no call site has to
    remember.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        index=True,
    )

    @property
    def is_deleted(self) -> bool:
        return self.deleted_at is not None


class TenantMixin:
    """Scopes a row to an organisation.

    Multi-tenancy is the single most expensive thing to retrofit, so the
    column exists from the first migration even before organisations are a
    user-facing feature. We use shared-schema (a discriminator column) rather
    than schema-per-tenant: at thousands of tenants, per-schema migrations
    become an operational burden, whereas one indexed column stays cheap.

    Isolation is therefore enforced in the repository layer — every query is
    filtered by ``organization_id``. Postgres row-level security is the
    intended second line of defence once auth lands, so that a missing filter
    is a failed query rather than a data leak.
    """

    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
